const COUNTRY_ES = {
  ALG: 'Argelia',
  ARG: 'Argentina',
  AUS: 'Australia',
  AUT: 'Austria',
  BEL: 'Bélgica',
  BOL: 'Bolivia',
  BRA: 'Brasil',
  CAN: 'Canadá',
  CHI: 'Chile',
  CIV: 'Costa de Marfil',
  CMR: 'Camerún',
  COL: 'Colombia',
  CRC: 'Costa Rica',
  CPV: 'Cabo Verde',
  CRO: 'Croacia',
  CUW: 'Curazao',
  CZE: 'Chequia',
  DEN: 'Dinamarca',
  ECU: 'Ecuador',
  EGY: 'Egipto',
  ENG: 'Inglaterra',
  ESP: 'España',
  FRA: 'Francia',
  GAB: 'Gabón',
  GER: 'Alemania',
  GHA: 'Ghana',
  GRE: 'Grecia',
  HAI: 'Haití',
  HON: 'Honduras',
  HUN: 'Hungría',
  IRL: 'Irlanda',
  IRN: 'Irán',
  IRQ: 'Irak',
  ITA: 'Italia',
  JOR: 'Jordania',
  JPN: 'Japón',
  KOR: 'Corea del Sur',
  KSA: 'Arabia Saudí',
  MAR: 'Marruecos',
  MEX: 'México',
  MLI: 'Mali',
  NED: 'Países Bajos',
  NGA: 'Nigeria',
  NIR: 'Irlanda del Norte',
  NOR: 'Noruega',
  NZL: 'Nueva Zelanda',
  OMA: 'Omán',
  PAN: 'Panamá',
  PAR: 'Paraguay',
  PER: 'Perú',
  POL: 'Polonia',
  POR: 'Portugal',
  QAT: 'Catar',
  ROU: 'Rumanía',
  RSA: 'Sudáfrica',
  SCO: 'Escocia',
  SEN: 'Senegal',
  SRB: 'Serbia',
  SUI: 'Suiza',
  SVK: 'Eslovaquia',
  SVN: 'Eslovenia',
  SWE: 'Suecia',
  TUN: 'Túnez',
  TUR: 'Turquía',
  UAE: 'Emiratos Árabes Unidos',
  UKR: 'Ucrania',
  URU: 'Uruguay',
  USA: 'Estados Unidos',
  UZB: 'Uzbekistán',
  VEN: 'Venezuela',
  WAL: 'Gales',
};

export function countryNameEs(code, fallback = '') {
  return COUNTRY_ES[String(code || '').toUpperCase()] || fallback;
}

export function localizeTeam(team) {
  if (!team || !team.code) return team;
  const name = countryNameEs(team.code, team.name);
  return name ? { ...team, name } : team;
}
